
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package olc1_proyecto1_202302220.analizador;

import java_cup.runtime.Symbol;
import java.util.LinkedList;
import olc1_proyecto1_202302220.*;
import utilidades.*;
import expresion.*;
import abstractas.*;
import instruccion.*;
import objetos.*;
import java.util.ArrayList;
import java.util.Arrays;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\071\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\005\007\000\002\006\004\000" +
    "\002\007\005\000\002\010\007\000\002\011\010\000\002" +
    "\011\006\000\002\011\004\000\002\012\007\000\002\013" +
    "\005\000\002\014\012\000\002\015\005\000\002\016\007" +
    "\000\002\017\011\000\002\020\005\000\002\020\005\000" +
    "\002\020\005\000\002\020\005\000\002\021\006\000\002" +
    "\022\014\000\002\032\003\000\002\032\003\000\002\024" +
    "\003\000\002\024\003\000\002\024\003\000\002\024\003" +
    "\000\002\024\003\000\002\024\003\000\002\024\003\000" +
    "\002\024\003\000\002\024\003\000\002\024\003\000\002" +
    "\024\003\000\002\024\003\000\002\024\003\000\002\025" +
    "\005\000\002\025\005\000\002\025\005\000\002\025\005" +
    "\000\002\025\005\000\002\025\005\000\002\026\005\000" +
    "\002\026\005\000\002\026\004\000\002\027\010\000\002" +
    "\027\006\000\002\027\010\000\002\027\010\000\002\030" +
    "\005\000\002\031\005\000\002\031\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\226\000\010\005\012\006\005\007\007\001\002\000" +
    "\012\002\ufffd\005\ufffd\006\ufffd\007\ufffd\001\002\000\004" +
    "\066\157\001\002\000\012\002\ufffc\005\ufffc\006\ufffc\007" +
    "\ufffc\001\002\000\004\056\142\001\002\000\012\002\ufffb" +
    "\005\ufffb\006\ufffb\007\ufffb\001\002\000\012\002\ufffe\005" +
    "\ufffe\006\ufffe\007\ufffe\001\002\000\004\066\017\001\002" +
    "\000\012\002\000\005\012\006\005\007\007\001\002\000" +
    "\004\002\015\001\002\000\004\002\001\001\002\000\012" +
    "\002\uffff\005\uffff\006\uffff\007\uffff\001\002\000\004\056" +
    "\020\001\002\000\004\012\021\001\002\000\004\063\140" +
    "\001\002\000\004\057\137\001\002\000\004\013\025\001" +
    "\002\000\004\057\ufff9\001\002\000\004\063\026\001\002" +
    "\000\004\054\027\001\002\000\006\014\032\016\031\001" +
    "\002\000\004\055\136\001\002\000\042\010\050\011\047" +
    "\017\037\020\044\021\033\022\042\023\056\027\057\030" +
    "\036\031\041\032\052\045\035\054\051\064\055\065\043" +
    "\067\046\001\002\000\042\010\050\011\047\017\037\020" +
    "\044\021\033\022\042\023\056\027\057\030\036\031\041" +
    "\032\052\045\035\054\051\064\055\065\043\067\046\001" +
    "\002\000\004\060\130\001\002\000\024\015\124\043\066" +
    "\044\074\046\067\047\070\050\071\051\072\052\073\053" +
    "\075\001\002\000\042\010\050\011\047\017\037\020\044" +
    "\021\033\022\042\023\056\027\057\030\036\031\041\032" +
    "\052\045\035\054\051\064\055\065\043\067\046\001\002" +
    "\000\036\015\uffde\037\uffde\043\uffde\044\uffde\046\uffde\047" +
    "\uffde\050\uffde\051\uffde\052\uffde\053\uffde\055\uffde\057\uffde" +
    "\061\uffde\062\uffde\001\002\000\004\060\116\001\002\000" +
    "\036\015\uffe1\037\uffe1\043\uffe1\044\uffe1\046\uffe1\047\uffe1" +
    "\050\uffe1\051\uffe1\052\uffe1\053\uffe1\055\uffe1\057\uffe1\061" +
    "\uffe1\062\uffe1\001\002\000\036\015\uffdc\037\uffdc\043\uffdc" +
    "\044\uffdc\046\uffdc\047\uffdc\050\uffdc\051\uffdc\052\uffdc\053" +
    "\uffdc\055\uffdc\057\uffdc\061\uffdc\062\uffdc\001\002\000\004" +
    "\060\111\001\002\000\036\015\uffd9\037\uffd9\043\uffd9\044" +
    "\uffd9\046\uffd9\047\uffd9\050\uffd9\051\uffd9\052\uffd9\053\uffd9" +
    "\055\uffd9\057\uffd9\061\uffd9\062\uffd9\001\002\000\004\060" +
    "\106\001\002\000\036\015\uffe3\037\uffe3\043\uffe3\044\uffe3" +
    "\046\uffe3\047\uffe3\050\uffe3\051\uffe3\052\uffe3\053\uffe3\055" +
    "\uffe3\057\uffe3\061\uffe3\062\uffe3\001\002\000\036\015\uffe0" +
    "\037\uffe0\043\uffe0\044\uffe0\046\uffe0\047\uffe0\050\uffe0\051" +
    "\uffe0\052\uffe0\053\uffe0\055\uffe0\057\uffe0\061\uffe0\062\uffe0" +
    "\001\002\000\040\013\uffe6\015\uffe6\037\uffe6\043\uffe6\044" +
    "\uffe6\046\uffe6\047\uffe6\050\uffe6\051\uffe6\052\uffe6\053\uffe6" +
    "\055\uffe6\057\uffe6\061\uffe6\062\uffe6\001\002\000\040\013" +
    "\uffe7\015\uffe7\037\uffe7\043\uffe7\044\uffe7\046\uffe7\047\uffe7" +
    "\050\uffe7\051\uffe7\052\uffe7\053\uffe7\055\uffe7\057\uffe7\061" +
    "\uffe7\062\uffe7\001\002\000\042\010\050\011\047\017\037" +
    "\020\044\021\033\022\042\023\056\027\057\030\036\031" +
    "\041\032\052\045\035\054\051\064\055\065\043\067\046" +
    "\001\002\000\036\015\uffdb\037\uffdb\043\uffdb\044\uffdb\046" +
    "\uffdb\047\uffdb\050\uffdb\051\uffdb\052\uffdb\053\uffdb\055\uffdb" +
    "\057\uffdb\061\uffdb\062\uffdb\001\002\000\036\015\uffe5\037" +
    "\uffe5\043\uffe5\044\uffe5\046\uffe5\047\uffe5\050\uffe5\051\uffe5" +
    "\052\uffe5\053\uffe5\055\uffe5\057\uffe5\061\uffe5\062\uffe5\001" +
    "\002\000\036\015\uffe4\037\uffe4\043\uffe4\044\uffe4\046\uffe4" +
    "\047\uffe4\050\uffe4\051\uffe4\052\uffe4\053\uffe4\055\uffe4\057" +
    "\uffe4\061\uffe4\062\uffe4\001\002\000\036\015\uffda\037\uffda" +
    "\043\uffda\044\uffda\046\uffda\047\uffda\050\uffda\051\uffda\052" +
    "\uffda\053\uffda\055\uffda\057\uffda\061\uffda\062\uffda\001\002" +
    "\000\036\015\uffdd\037\uffdd\043\uffdd\044\uffdd\046\uffdd\047" +
    "\uffdd\050\uffdd\051\uffdd\052\uffdd\053\uffdd\055\uffdd\057\uffdd" +
    "\061\uffdd\062\uffdd\001\002\000\036\015\uffdf\037\uffdf\043" +
    "\uffdf\044\uffdf\046\uffdf\047\uffdf\050\uffdf\051\uffdf\052\uffdf" +
    "\053\uffdf\055\uffdf\057\uffdf\061\uffdf\062\uffdf\001\002\000" +
    "\036\015\uffe2\037\uffe2\043\uffe2\044\uffe2\046\uffe2\047\uffe2" +
    "\050\uffe2\051\uffe2\052\uffe2\053\uffe2\055\uffe2\057\uffe2\061" +
    "\uffe2\062\uffe2\001\002\000\026\043\066\044\074\046\067" +
    "\047\070\050\071\051\072\052\073\053\075\055\uffc9\062" +
    "\uffc9\001\002\000\006\055\064\062\063\001\002\000\042" +
    "\010\050\011\047\017\037\020\044\021\033\022\042\023" +
    "\056\027\057\030\036\031\041\032\052\045\035\054\051" +
    "\064\055\065\043\067\046\001\002\000\036\015\uffcb\037" +
    "\uffcb\043\uffcb\044\uffcb\046\uffcb\047\uffcb\050\uffcb\051\uffcb" +
    "\052\uffcb\053\uffcb\055\uffcb\057\uffcb\061\uffcb\062\uffcb\001" +
    "\002\000\026\043\066\044\074\046\067\047\070\050\071" +
    "\051\072\052\073\053\075\055\uffca\062\uffca\001\002\000" +
    "\042\010\050\011\047\017\037\020\044\021\033\022\042" +
    "\023\056\027\057\030\036\031\041\032\052\045\035\054" +
    "\051\064\055\065\043\067\046\001\002\000\042\010\050" +
    "\011\047\017\037\020\044\021\033\022\042\023\056\027" +
    "\057\030\036\031\041\032\052\045\035\054\051\064\055" +
    "\065\043\067\046\001\002\000\042\010\050\011\047\017" +
    "\037\020\044\021\033\022\042\023\056\027\057\030\036" +
    "\031\041\032\052\045\035\054\051\064\055\065\043\067" +
    "\046\001\002\000\042\010\050\011\047\017\037\020\044" +
    "\021\033\022\042\023\056\027\057\030\036\031\041\032" +
    "\052\045\035\054\051\064\055\065\043\067\046\001\002" +
    "\000\042\010\050\011\047\017\037\020\044\021\033\022" +
    "\042\023\056\027\057\030\036\031\041\032\052\045\035" +
    "\054\051\064\055\065\043\067\046\001\002\000\042\010" +
    "\050\011\047\017\037\020\044\021\033\022\042\023\056" +
    "\027\057\030\036\031\041\032\052\045\035\054\051\064" +
    "\055\065\043\067\046\001\002\000\042\010\050\011\047" +
    "\017\037\020\044\021\033\022\042\023\056\027\057\030" +
    "\036\031\041\032\052\045\035\054\051\064\055\065\043" +
    "\067\046\001\002\000\042\010\050\011\047\017\037\020" +
    "\044\021\033\022\042\023\056\027\057\030\036\031\041" +
    "\032\052\045\035\054\051\064\055\065\043\067\046\001" +
    "\002\000\036\015\uffd3\037\uffd3\043\uffd3\044\uffd3\046\uffd3" +
    "\047\uffd3\050\uffd3\051\uffd3\052\uffd3\053\uffd3\055\uffd3\057" +
    "\uffd3\061\uffd3\062\uffd3\001\002\000\036\015\uffd1\037\uffd1" +
    "\043\uffd1\044\uffd1\046\uffd1\047\uffd1\050\uffd1\051\uffd1\052" +
    "\uffd1\053\uffd1\055\uffd1\057\uffd1\061\uffd1\062\uffd1\001\002" +
    "\000\036\015\uffd4\037\uffd4\043\uffd4\044\uffd4\046\uffd4\047" +
    "\uffd4\050\uffd4\051\uffd4\052\uffd4\053\uffd4\055\uffd4\057\uffd4" +
    "\061\uffd4\062\uffd4\001\002\000\036\015\uffd5\037\uffd5\043" +
    "\uffd5\044\uffd5\046\uffd5\047\uffd5\050\uffd5\051\uffd5\052\uffd5" +
    "\053\uffd5\055\uffd5\057\uffd5\061\uffd5\062\uffd5\001\002\000" +
    "\036\015\uffd6\037\uffd6\043\uffd6\044\uffd6\046\uffd6\047\uffd6" +
    "\050\uffd6\051\uffd6\052\uffd6\053\uffd6\055\uffd6\057\uffd6\061" +
    "\uffd6\062\uffd6\001\002\000\036\015\uffd7\037\uffd7\043\uffd7" +
    "\044\uffd7\046\uffd7\047\uffd7\050\uffd7\051\uffd7\052\uffd7\053" +
    "\uffd7\055\uffd7\057\uffd7\061\uffd7\062\uffd7\001\002\000\036" +
    "\015\uffd8\037\uffd8\043\uffd8\044\uffd8\046\uffd8\047\uffd8\050" +
    "\uffd8\051\uffd8\052\uffd8\053\uffd8\055\uffd8\057\uffd8\061\uffd8" +
    "\062\uffd8\001\002\000\036\015\uffd2\037\uffd2\043\uffd2\044" +
    "\uffd2\046\uffd2\047\uffd2\050\uffd2\051\uffd2\052\uffd2\053\uffd2" +
    "\055\uffd2\057\uffd2\061\uffd2\062\uffd2\001\002\000\042\010" +
    "\050\011\047\017\037\020\044\021\033\022\042\023\056" +
    "\027\057\030\036\031\041\032\052\045\035\054\051\064" +
    "\055\065\043\067\046\001\002\000\024\043\066\044\074" +
    "\046\067\047\070\050\071\051\072\052\073\053\075\061" +
    "\110\001\002\000\036\015\uffce\037\uffce\043\uffce\044\uffce" +
    "\046\uffce\047\uffce\050\uffce\051\uffce\052\uffce\053\uffce\055" +
    "\uffce\057\uffce\061\uffce\062\uffce\001\002\000\042\010\050" +
    "\011\047\017\037\020\044\021\033\022\042\023\056\027" +
    "\057\030\036\031\041\032\052\045\035\054\051\064\055" +
    "\065\043\067\046\001\002\000\024\043\066\044\074\046" +
    "\067\047\070\050\071\051\072\052\073\053\075\062\113" +
    "\001\002\000\042\010\050\011\047\017\037\020\044\021" +
    "\033\022\042\023\056\027\057\030\036\031\041\032\052" +
    "\045\035\054\051\064\055\065\043\067\046\001\002\000" +
    "\024\043\066\044\074\046\067\047\070\050\071\051\072" +
    "\052\073\053\075\061\115\001\002\000\036\015\uffcd\037" +
    "\uffcd\043\uffcd\044\uffcd\046\uffcd\047\uffcd\050\uffcd\051\uffcd" +
    "\052\uffcd\053\uffcd\055\uffcd\057\uffcd\061\uffcd\062\uffcd\001" +
    "\002\000\042\010\050\011\047\017\037\020\044\021\033" +
    "\022\042\023\056\027\057\030\036\031\041\032\052\045" +
    "\035\054\051\064\055\065\043\067\046\001\002\000\024" +
    "\043\066\044\074\046\067\047\070\050\071\051\072\052" +
    "\073\053\075\062\120\001\002\000\042\010\050\011\047" +
    "\017\037\020\044\021\033\022\042\023\056\027\057\030" +
    "\036\031\041\032\052\045\035\054\051\064\055\065\043" +
    "\067\046\001\002\000\024\043\066\044\074\046\067\047" +
    "\070\050\071\051\072\052\073\053\075\061\122\001\002" +
    "\000\036\015\uffcf\037\uffcf\043\uffcf\044\uffcf\046\uffcf\047" +
    "\uffcf\050\uffcf\051\uffcf\052\uffcf\053\uffcf\055\uffcf\057\uffcf" +
    "\061\uffcf\062\uffcf\001\002\000\036\015\uffd0\037\uffd0\043" +
    "\uffd0\044\uffd0\046\uffd0\047\uffd0\050\uffd0\051\uffd0\052\uffd0" +
    "\053\uffd0\055\uffd0\057\uffd0\061\uffd0\062\uffd0\001\002\000" +
    "\042\010\050\011\047\017\037\020\044\021\033\022\042" +
    "\023\056\027\057\030\036\031\041\032\052\045\035\054" +
    "\051\064\055\065\043\067\046\001\002\000\026\043\066" +
    "\044\074\046\067\047\070\050\071\051\072\052\073\053" +
    "\075\055\ufff5\062\126\001\002\000\006\014\032\016\031" +
    "\001\002\000\004\055\ufff6\001\002\000\042\010\050\011" +
    "\047\017\037\020\044\021\033\022\042\023\056\027\057" +
    "\030\036\031\041\032\052\045\035\054\051\064\055\065" +
    "\043\067\046\001\002\000\024\043\066\044\074\046\067" +
    "\047\070\050\071\051\072\052\073\053\075\062\132\001" +
    "\002\000\042\010\050\011\047\017\037\020\044\021\033" +
    "\022\042\023\056\027\057\030\036\031\041\032\052\045" +
    "\035\054\051\064\055\065\043\067\046\001\002\000\024" +
    "\043\066\044\074\046\067\047\070\050\071\051\072\052" +
    "\073\053\075\061\134\001\002\000\036\015\uffcc\037\uffcc" +
    "\043\uffcc\044\uffcc\046\uffcc\047\uffcc\050\uffcc\051\uffcc\052" +
    "\uffcc\053\uffcc\055\uffcc\057\uffcc\061\uffcc\062\uffcc\001\002" +
    "\000\024\043\066\044\074\046\067\047\070\050\071\051" +
    "\072\052\073\053\075\055\ufff4\001\002\000\004\057\ufff7" +
    "\001\002\000\012\002\ufffa\005\ufffa\006\ufffa\007\ufffa\001" +
    "\002\000\006\010\050\011\047\001\002\000\004\013\ufff8" +
    "\001\002\000\004\040\144\001\002\000\004\057\156\001" +
    "\002\000\004\054\145\001\002\000\004\066\146\001\002" +
    "\000\004\055\147\001\002\000\004\041\150\001\002\000" +
    "\004\056\151\001\002\000\004\042\152\001\002\000\004" +
    "\063\153\001\002\000\042\010\050\011\047\017\037\020" +
    "\044\021\033\022\042\023\056\027\057\030\036\031\041" +
    "\032\052\045\035\054\051\064\055\065\043\067\046\001" +
    "\002\000\024\043\066\044\074\046\067\047\070\050\071" +
    "\051\072\052\073\053\075\057\155\001\002\000\004\057" +
    "\uffe8\001\002\000\012\002\uffe9\005\uffe9\006\uffe9\007\uffe9" +
    "\001\002\000\004\056\160\001\002\000\004\024\161\001" +
    "\002\000\004\025\222\001\002\000\004\057\221\001\002" +
    "\000\004\026\164\001\002\000\004\063\217\001\002\000" +
    "\004\037\166\001\002\000\004\063\170\001\002\000\004" +
    "\057\ufff2\001\002\000\004\056\171\001\002\000\012\033" +
    "\175\034\173\035\172\036\177\001\002\000\004\063\215" +
    "\001\002\000\004\063\213\001\002\000\004\057\212\001" +
    "\002\000\004\063\210\001\002\000\004\062\202\001\002" +
    "\000\004\063\200\001\002\000\042\010\050\011\047\017" +
    "\037\020\044\021\033\022\042\023\056\027\057\030\036" +
    "\031\041\032\052\045\035\054\051\064\055\065\043\067" +
    "\046\001\002\000\026\043\066\044\074\046\067\047\070" +
    "\050\071\051\072\052\073\053\075\057\uffea\062\uffea\001" +
    "\002\000\012\033\175\034\173\035\172\036\177\001\002" +
    "\000\004\062\204\001\002\000\012\033\175\034\173\035" +
    "\172\036\177\001\002\000\004\062\206\001\002\000\012" +
    "\033\175\034\173\035\172\036\177\001\002\000\004\057" +
    "\uffee\001\002\000\042\010\050\011\047\017\037\020\044" +
    "\021\033\022\042\023\056\027\057\030\036\031\041\032" +
    "\052\045\035\054\051\064\055\065\043\067\046\001\002" +
    "\000\026\043\066\044\074\046\067\047\070\050\071\051" +
    "\072\052\073\053\075\057\uffed\062\uffed\001\002\000\004" +
    "\057\uffef\001\002\000\042\010\050\011\047\017\037\020" +
    "\044\021\033\022\042\023\056\027\057\030\036\031\041" +
    "\032\052\045\035\054\051\064\055\065\043\067\046\001" +
    "\002\000\026\043\066\044\074\046\067\047\070\050\071" +
    "\051\072\052\073\053\075\057\uffec\062\uffec\001\002\000" +
    "\042\010\050\011\047\017\037\020\044\021\033\022\042" +
    "\023\056\027\057\030\036\031\041\032\052\045\035\054" +
    "\051\064\055\065\043\067\046\001\002\000\026\043\066" +
    "\044\074\046\067\047\070\050\071\051\072\052\073\053" +
    "\075\057\uffeb\062\uffeb\001\002\000\042\010\050\011\047" +
    "\017\037\020\044\021\033\022\042\023\056\027\057\030" +
    "\036\031\041\032\052\045\035\054\051\064\055\065\043" +
    "\067\046\001\002\000\024\037\ufff0\043\066\044\074\046" +
    "\067\047\070\050\071\051\072\052\073\053\075\001\002" +
    "\000\012\002\ufff3\005\ufff3\006\ufff3\007\ufff3\001\002\000" +
    "\004\063\223\001\002\000\004\054\224\001\002\000\004" +
    "\066\225\001\002\000\004\062\226\001\002\000\004\066" +
    "\227\001\002\000\004\055\230\001\002\000\004\026\ufff1" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\226\000\016\002\013\003\012\004\010\005\003\012" +
    "\005\021\007\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\004\015\005\003" +
    "\012\005\021\007\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\006\021" +
    "\007\022\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\010\023\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\027\001\001\000\002\001" +
    "\001\000\016\024\134\025\052\026\053\027\057\030\037" +
    "\032\044\001\001\000\016\024\033\025\052\026\053\027" +
    "\057\030\037\032\044\001\001\000\002\001\001\000\002" +
    "\001\001\000\016\024\122\025\052\026\053\027\057\030" +
    "\037\032\044\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\024" +
    "\060\025\052\026\053\027\057\030\037\031\061\032\044" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\024\064\025\052\026\053\027\057\030\037\032\044" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\024" +
    "\104\025\052\026\053\027\057\030\037\032\044\001\001" +
    "\000\016\024\103\025\052\026\053\027\057\030\037\032" +
    "\044\001\001\000\016\024\102\025\052\026\053\027\057" +
    "\030\037\032\044\001\001\000\016\024\101\025\052\026" +
    "\053\027\057\030\037\032\044\001\001\000\016\024\100" +
    "\025\052\026\053\027\057\030\037\032\044\001\001\000" +
    "\016\024\077\025\052\026\053\027\057\030\037\032\044" +
    "\001\001\000\016\024\076\025\052\026\053\027\057\030" +
    "\037\032\044\001\001\000\016\024\075\025\052\026\053" +
    "\027\057\030\037\032\044\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\024\106\025\052\026\053\027\057\030\037" +
    "\032\044\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\024\111\025\052\026\053\027\057\030\037\032\044" +
    "\001\001\000\002\001\001\000\016\024\113\025\052\026" +
    "\053\027\057\030\037\032\044\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\024\116\025\052\026\053\027" +
    "\057\030\037\032\044\001\001\000\002\001\001\000\016" +
    "\024\120\025\052\026\053\027\057\030\037\032\044\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\016\024\124\025\052\026\053\027\057\030\037\032" +
    "\044\001\001\000\002\001\001\000\004\011\126\001\001" +
    "\000\002\001\001\000\016\024\130\025\052\026\053\027" +
    "\057\030\037\032\044\001\001\000\002\001\001\000\016" +
    "\024\132\025\052\026\053\027\057\030\037\032\044\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\032\140\001" +
    "\001\000\002\001\001\000\004\022\142\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\024\153\025\052\026\053\027" +
    "\057\030\037\032\044\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\013" +
    "\161\014\162\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\015\164\001\001\000\002\001\001\000\004\016" +
    "\166\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\017\173\020\175\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\024\200\025" +
    "\052\026\053\027\057\030\037\032\044\001\001\000\002" +
    "\001\001\000\004\020\202\001\001\000\002\001\001\000" +
    "\004\020\204\001\001\000\002\001\001\000\004\020\206" +
    "\001\001\000\002\001\001\000\016\024\210\025\052\026" +
    "\053\027\057\030\037\032\044\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\024\213\025\052\026\053\027" +
    "\057\030\037\032\044\001\001\000\002\001\001\000\016" +
    "\024\215\025\052\026\053\027\057\030\037\032\044\001" +
    "\001\000\002\001\001\000\016\024\217\025\052\026\053" +
    "\027\057\030\037\032\044\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Codigo Java
    public ArrayList<Instruccion> sentencias;



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= ini EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // ini ::= iniciar 
            {
              Object RESULT =null;
		int iniciarleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iniciarright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<Instruccion> iniciar = (ArrayList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 sentencias = iniciar; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ini",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // iniciar ::= iniciar instruccion 
            {
              ArrayList<Instruccion> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Instruccion> l = (ArrayList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion i = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = l; RESULT.add(i); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("iniciar",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // iniciar ::= instruccion 
            {
              ArrayList<Instruccion> RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion i = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ArrayList<>(Arrays.asList(i));  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("iniciar",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion ::= bloque_Strategy 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		CrearEstrategia e = (CrearEstrategia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= bloque_Match 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion e = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= bloque_Main 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion e = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // bloque_Strategy ::= STRATEGY ID ABRE_LLAVE strategy_Cuerpo CIERRA_LLAVE 
            {
              CrearEstrategia RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int instleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int instright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		InstruccionEstrategia inst = (InstruccionEstrategia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new CrearEstrategia(n, inst);      System.out.println("Se leyó todooooooooooo"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_Strategy",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // strategy_Cuerpo ::= regla_Inicial reglas 
            {
              InstruccionEstrategia RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion i = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<Regla> r = (ArrayList<Regla>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT= new InstruccionEstrategia(i,r); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("strategy_Cuerpo",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // regla_Inicial ::= INITIAL DOS_PUNTOS decision 
            {
              Expresion RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion d = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT= d; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("regla_Inicial",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // reglas ::= RULES DOS_PUNTOS ABRE_CORCHETE lista_Reglas CIERRA_CORCHETE 
            {
              ArrayList<Regla> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Regla> l = (ArrayList<Regla>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT=l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("reglas",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // lista_Reglas ::= IF expresion THEN expresion COMA lista_Reglas 
            {
              ArrayList<Regla> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Expresion c = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<Regla> l = (ArrayList<Regla>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = l; RESULT.add(new Regla(c, a)); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_Reglas",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_Reglas ::= IF expresion THEN expresion 
            {
              ArrayList<Regla> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion c = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ArrayList<Regla>(Arrays.asList(new Regla(c, a))); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_Reglas",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // lista_Reglas ::= ELSE expresion 
            {
              ArrayList<Regla> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ArrayList<Regla>(Arrays.asList(new Regla(null, a))); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_Reglas",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // bloque_Match ::= MATCH ID ABRE_LLAVE match_Cuerpo CIERRA_LLAVE 
            {
              Instruccion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int instleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int instright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		InstruccionPartida inst = (InstruccionPartida)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new CrearPartida(n, inst); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_Match",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // match_Cuerpo ::= jugadores rondas puntuaciones 
            {
              InstruccionPartida RESULT =null;
		int jleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int jright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Jugadores j = (Jugadores)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion r = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Puntos p = (Puntos)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new InstruccionPartida(j, r, p); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("match_Cuerpo",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // jugadores ::= PLAYERS STRATEGIES DOS_PUNTOS ABRE_CORCHETE ID COMA ID CIERRA_CORCHETE 
            {
              Jugadores RESULT =null;
		int j1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int j1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String j1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int j2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int j2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String j2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Jugadores(j1, j2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("jugadores",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // rondas ::= ROUNDS DOS_PUNTOS expresion 
            {
              Expresion RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = exp; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("rondas",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // puntuaciones ::= SCORING DOS_PUNTOS ABRE_LLAVE puntos CIERRA_LLAVE 
            {
              Puntos RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Puntos p = (Puntos)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = p; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("puntuaciones",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // puntos ::= puntuacion COMA puntuacion COMA puntuacion COMA puntuacion 
            {
              Puntos RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		Expresion c = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Expresion d = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int trleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int trright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion tr = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int taleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int taright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion ta = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Puntos(c, d, tr, ta); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("puntos",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // puntuacion ::= MUTUAL_COOPERATION DOS_PUNTOS expresion 
            {
              Expresion RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT =  exp; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("puntuacion",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // puntuacion ::= MUTUAL_DEFECTION DOS_PUNTOS expresion 
            {
              Expresion RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT =  exp; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("puntuacion",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // puntuacion ::= BETRAYAL_REWARD DOS_PUNTOS expresion 
            {
              Expresion RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT =  exp; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("puntuacion",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // puntuacion ::= BETRAYAL_PUNISHMENT DOS_PUNTOS expresion 
            {
              Expresion RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT =  exp; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("puntuacion",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // bloque_Main ::= MAIN ABRE_LLAVE main_Cuerpo CIERRA_LLAVE 
            {
              Instruccion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Inicio(p); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_Main",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // main_Cuerpo ::= RUN ABRE_CORCHETE ID CIERRA_CORCHETE WITH ABRE_LLAVE SEED DOS_PUNTOS expresion CIERRA_LLAVE 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		 RESULT = id; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("main_Cuerpo",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // decision ::= C 
            {
              Expresion RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Primitiva(d, TipoTipo.DECISION); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decision",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // decision ::= D 
            {
              Expresion RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Primitiva(d, TipoTipo.DECISION); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decision",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expresion ::= comparacion 
            {
              Expresion RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion r = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT =r; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expresion ::= logica 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expresion ::= decision 
            {
              Expresion RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion d = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = d; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expresion ::= funcion 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expresion ::= lista 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expresion ::= RANDOM 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expresion ::= OPPONENT_HISTORY 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expresion ::= SELF_HISTORY 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expresion ::= ROUND_NUMBER 
            {
              Expresion RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String r = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT =new RondaActual(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expresion ::= TRUE 
            {
              Expresion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Primitiva(p,TipoTipo.BOOLEANO); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expresion ::= FALSE 
            {
              Expresion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Primitiva(p,TipoTipo.BOOLEANO); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expresion ::= ENTERO 
            {
              Expresion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Primitiva(p,TipoTipo.ENTERO); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expresion ::= FLOTANTE 
            {
              Expresion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Primitiva(p,TipoTipo.FLOTANTE); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // comparacion ::= expresion IGUAL expresion 
            {
              Expresion RESULT =null;
		int exp1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int exp1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion exp1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int exp2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exp2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Comparacion(exp1,op,exp2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // comparacion ::= expresion NO_IGUAL expresion 
            {
              Expresion RESULT =null;
		int exp1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int exp1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion exp1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int exp2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exp2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Comparacion(exp1,op,exp2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // comparacion ::= expresion MENOR expresion 
            {
              Expresion RESULT =null;
		int exp1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int exp1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion exp1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int exp2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exp2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Comparacion(exp1,op,exp2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // comparacion ::= expresion MAYOR expresion 
            {
              Expresion RESULT =null;
		int exp1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int exp1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion exp1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int exp2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exp2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Comparacion(exp1,op,exp2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // comparacion ::= expresion MENOR_IGUAL expresion 
            {
              Expresion RESULT =null;
		int exp1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int exp1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion exp1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int exp2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exp2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Comparacion(exp1,op,exp2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // comparacion ::= expresion MAYOR_IGUAL expresion 
            {
              Expresion RESULT =null;
		int exp1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int exp1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion exp1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int exp2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exp2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Comparacion(exp1,op,exp2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // logica ::= expresion AND expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("logica",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // logica ::= expresion OR expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("logica",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // logica ::= NOT expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("logica",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // funcion ::= GET_MOVE ABRE_PARENTESIS expresion COMA expresion CIERRA_PARENTESIS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // funcion ::= LAST_MOVE ABRE_PARENTESIS expresion CIERRA_PARENTESIS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // funcion ::= GET_MOVES_COUNT ABRE_PARENTESIS expresion COMA expresion CIERRA_PARENTESIS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // funcion ::= GET_LAST_N_MOVES ABRE_PARENTESIS expresion COMA expresion CIERRA_PARENTESIS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // lista ::= ABRE_CORCHETE elemento CIERRA_CORCHETE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // elemento ::= elemento COMA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("elemento",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // elemento ::= expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("elemento",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
