
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package olc1_proyecto1_202302220.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MUTUAL_COOPERATION = 25;
  public static final int MUTUAL_DEFECTION = 26;
  public static final int GET_MOVES_COUNT = 16;
  public static final int RANDOM = 53;
  public static final int WITH = 31;
  public static final int ENTERO = 50;
  public static final int CIERRA_PARENTESIS = 47;
  public static final int SCORING = 29;
  public static final int DOS_PUNTOS = 49;
  public static final int ABRE_PARENTESIS = 46;
  public static final int MATCH = 4;
  public static final int RULES = 9;
  public static final int D = 7;
  public static final int C = 6;
  public static final int ABRE_LLAVE = 44;
  public static final int NOT = 35;
  public static final int AND = 33;
  public static final int IGUAL = 36;
  public static final int GET_LAST_N_MOVES = 15;
  public static final int OR = 34;
  public static final int STRATEGIES = 19;
  public static final int CIERRA_CORCHETE = 43;
  public static final int MAIN = 5;
  public static final int IF = 10;
  public static final int ID = 52;
  public static final int INITIAL = 8;
  public static final int EOF = 0;
  public static final int ROUNDS = 20;
  public static final int TRUE = 23;
  public static final int BETRAYAL_PUNISHMENT = 28;
  public static final int error = 1;
  public static final int COMA = 48;
  public static final int PLAYERS = 18;
  public static final int MENOR = 38;
  public static final int ABRE_CORCHETE = 42;
  public static final int STRATEGY = 3;
  public static final int ERROR_LEXICO = 2;
  public static final int NO_IGUAL = 37;
  public static final int BETRAYAL_REWARD = 27;
  public static final int MAYOR = 39;
  public static final int SELF_HISTORY = 22;
  public static final int ROUND_NUMBER = 17;
  public static final int LAST_MOVE = 14;
  public static final int ELSE = 12;
  public static final int GET_MOVE = 13;
  public static final int MAYOR_IGUAL = 41;
  public static final int THEN = 11;
  public static final int SEED = 32;
  public static final int MENOR_IGUAL = 40;
  public static final int OPPONENT_HISTORY = 21;
  public static final int FALSE = 24;
  public static final int CIERRA_LLAVE = 45;
  public static final int RUN = 30;
  public static final int FLOTANTE = 51;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ERROR_LEXICO",
  "STRATEGY",
  "MATCH",
  "MAIN",
  "C",
  "D",
  "INITIAL",
  "RULES",
  "IF",
  "THEN",
  "ELSE",
  "GET_MOVE",
  "LAST_MOVE",
  "GET_LAST_N_MOVES",
  "GET_MOVES_COUNT",
  "ROUND_NUMBER",
  "PLAYERS",
  "STRATEGIES",
  "ROUNDS",
  "OPPONENT_HISTORY",
  "SELF_HISTORY",
  "TRUE",
  "FALSE",
  "MUTUAL_COOPERATION",
  "MUTUAL_DEFECTION",
  "BETRAYAL_REWARD",
  "BETRAYAL_PUNISHMENT",
  "SCORING",
  "RUN",
  "WITH",
  "SEED",
  "AND",
  "OR",
  "NOT",
  "IGUAL",
  "NO_IGUAL",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "ABRE_CORCHETE",
  "CIERRA_CORCHETE",
  "ABRE_LLAVE",
  "CIERRA_LLAVE",
  "ABRE_PARENTESIS",
  "CIERRA_PARENTESIS",
  "COMA",
  "DOS_PUNTOS",
  "ENTERO",
  "FLOTANTE",
  "ID",
  "RANDOM"
  };
}

